#!/bin/bash
# ============================================================
# setup.sh — One-shot nexus environment setup (venv at ~/.nexus/venv)
#
# Usage:
#   bash setup.sh              # install venv + deps, write ~/.nexus/activate.sh
#   bash setup.sh --reinstall  # wipe ~/.nexus/venv first, then reinstall
#   bash setup.sh --alias      # additionally append `nexus-activate` to ~/.bashrc
#
# Why ~/.nexus/venv ?
#   The venv lives outside the nexus source tree so that replacing/updating
#   the repo (git pull, rsync, etc.) does NOT wipe the installed packages.
#   A single venv is shared across all checkouts on this machine.
# ============================================================

set -e

# ── Flags ────────────────────────────────────────────────────
REINSTALL=0
ADD_ALIAS=0
for arg in "$@"; do
    case "$arg" in
        --reinstall) REINSTALL=1 ;;
        --alias)     ADD_ALIAS=1 ;;
        -h|--help)
            sed -n '2,15p' "$0"; exit 0 ;;
        *) echo "[ERROR] Unknown argument: $arg"; exit 1 ;;
    esac
done

NEXUS_HOME="${HOME}/.nexus"
VENV_DIR="${NEXUS_HOME}/venv"
ACTIVATE_SH="${NEXUS_HOME}/activate.sh"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "======================================"
echo " nexus — Environment Setup"
echo "======================================"
echo "  Repo : ${REPO_DIR}"
echo "  Venv : ${VENV_DIR}"
echo ""

mkdir -p "${NEXUS_HOME}"

# ── (Optional) wipe existing venv ────────────────────────────
if [ "$REINSTALL" = "1" ] && [ -d "${VENV_DIR}" ]; then
    echo "[--reinstall] Removing existing venv: ${VENV_DIR}"
    rm -rf "${VENV_DIR}"
fi

# ── Create venv ──────────────────────────────────────────────
if [ ! -d "${VENV_DIR}" ]; then
    python3 -m venv "${VENV_DIR}"
    echo "[OK] venv created at ${VENV_DIR}"
else
    echo "[SKIP] venv already exists at ${VENV_DIR}"
fi

# shellcheck disable=SC1090
source "${VENV_DIR}/bin/activate"
pip install --upgrade pip -q

pip install \
    mlflow==2.13.0 \
    tbparse==0.0.8 \
    tensorboard==2.16.2 \
    tensorboardX \
    pandas \
    rich \
    -q

echo "[OK] All packages installed"

# ── Generate ~/.nexus/activate.sh (source-from-anywhere helper) ──
cat > "${ACTIVATE_SH}" <<EOF
# Generated by nexus setup.sh — do not edit by hand.
# Source this from any shell to activate the nexus venv:
#   source ${ACTIVATE_SH}
export NEXUS_HOME="${NEXUS_HOME}"
export NEXUS_REPO="${REPO_DIR}"
# shellcheck disable=SC1091
source "${VENV_DIR}/bin/activate"
EOF
chmod +x "${ACTIVATE_SH}"
echo "[OK] Wrote ${ACTIVATE_SH}"

# ── (Optional) register `nexus-activate` alias in ~/.bashrc ──
if [ "$ADD_ALIAS" = "1" ]; then
    BASHRC="${HOME}/.bashrc"
    MARKER="# --- nexus-activate alias ---"
    if grep -qF "${MARKER}" "${BASHRC}" 2>/dev/null; then
        echo "[SKIP] nexus-activate alias already present in ${BASHRC}"
    else
        {
            echo ""
            echo "${MARKER}"
            echo "alias nexus-activate='source ${ACTIVATE_SH}'"
            echo "# --- end nexus-activate alias ---"
        } >> "${BASHRC}"
        echo "[OK] Appended nexus-activate alias to ${BASHRC}"
        echo "     Run 'source ${BASHRC}' (or open a new shell) to pick it up."
    fi
fi

echo ""
echo "--------------------------------------"
echo " Done."
echo ""
echo " Activate (any shell, any directory):"
echo "   source ~/.nexus/activate.sh"
if [ "$ADD_ALIAS" = "1" ] || grep -qF "# --- nexus-activate alias ---" "${HOME}/.bashrc" 2>/dev/null; then
    echo "   # or, with the alias:"
    echo "   nexus-activate"
else
    echo ""
    echo " To register a shorter alias (\`nexus-activate\`), re-run:"
    echo "   bash setup.sh --alias"
fi
echo ""
echo " Reinstall from scratch (e.g. after the repo is overwritten):"
echo "   bash setup.sh --reinstall"
echo "--------------------------------------"
